it('this is an intermediate level test', () => {
cy.visit('/')
cy.wait(3000)
cy.get('#inter_example > .round-tabs > .glyphicon').click()
cy.get('.list-group > [href="./input-form-demo.html"]').click()
cy.get(':nth-child(2) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(2) > .inputGroupContainer > .input-group > .form-control').type('Tobi')
cy.get(':nth-child(3) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(3) > .inputGroupContainer > .input-group > .form-control').type('Adelua')
cy.get(':nth-child(4) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(4) > .inputGroupContainer > .input-group > .form-control').type('oadelua@gmail.com')
cy.get(':nth-child(5) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(5) > .inputGroupContainer > .input-group > .form-control').type('8457234678')
cy.get(':nth-child(6) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(6) > .inputGroupContainer > .input-group > .form-control').type('Presidential road, Georgia')
cy.get(':nth-child(7) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(7) > .inputGroupContainer > .input-group > .form-control').type('Carolina')
cy.get('.selectContainer > .input-group > .form-control').select([4])
cy.get(':nth-child(9) > .inputGroupContainer > .input-group > .form-control').click()
cy.get(':nth-child(9) > .inputGroupContainer > .input-group > .form-control').type('72764')
cy.get(':nth-child(10) > .inputGroupContainer > .input-group > .form-control').click
cy.get(':nth-child(10) > .inputGroupContainer > .input-group > .form-control').type('hhtps://cypress.io')
cy.get(':nth-child(11) > div.col-md-4 > :nth-child(2)').click()
cy.get(':nth-child(2) > label > input').click ()
cy.get(':nth-child(12) > .inputGroupContainer > .input-group > .form-control').click ()
cy.get(':nth-child(12) > .inputGroupContainer > .input-group > .form-control').type('Cypress Automation Test')
cy.get('.btn').click()
})
